[project]
name = "invest-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ccxt>=4.4.88",
    "matplotlib>=3.9.4",
    "pandas>=2.3.0",
    "ruff>=0.11.13",
    "yfinance>=0.2.61",
]
